### ISSUE TITLE
dependencies issues

### ISSUE THREAD

**Issue by misaalanshori** [Sh3llcod3/Airscript-ng#2]
It keeps trying to compile mdk4:
[i] The following packages may need compilation: aircrack-ng, reaver, pixiewps and MDK4.
[i] This may take up to 5 mins on older systems. This will only happen once (on first run).
[i] Proceed and install? y/n >> y
Cloning into 'mdk4'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 329 (delta 0), reused 3 (delta 0), pack-reused 324
Receiving objects: 100% (329/329), 335.91 KiB | 389.00 KiB/s, done.
Resolving deltas: 100% (171/171), done.
Makefile:13: *** Recursive variable 'PREFIX' references itself (eventually).  Stop.
[-] All dependancies are met. Make sure you have correct drivers!

but when i try to use it:
#: 1 Interface: wlan0 Chipset: unable to detect for sdio 0x024c:0xb723
#: 2 Interface: wlx18a6f71acd57 Chipset: Atheros Communications, Inc. AR9271 802.11n

[?] What card do you want to use? (enter #) >> 2
[i] Use wlx18a6f71acd57? y/n >> y
[ok] wlx18a6f71acd57 is in Monitor mode.

[ok] You're all set.
[ok] You can press Ctrl+C to stop, anytime.

[i] Start Beacon-Flood? y/n >> y
/bin/sh: 1: /home/adminispwd/.airscriptNG/mdk/*/src/mdk4: not found

[+] Head to [m]enu or [q]uit? m/q >> 

It was working before I reinstalled Ubuntu...

also, option 2 (pixiewps) wont work because when i use ctrl-c after the target was detected the script exits to "[+] Head to [m]enu or [q]uit? m/q >>" instead of continuing

**Comment by Sh3llcod3** [comment]
@misaalanshori I've fixed a minor broken path issue that was causing MDK4 not to compile. Beacon Flood should now work as intended. I've tested pixiewps and I can't replicate the error you described? Could it be that you are pressing ctrl-c more than once causing the script to exit?

**Comment by misaalanshori** [comment]
Ok, i can just clone it again right?

**Comment by Sh3llcod3** [comment]
@misaalanshori Yep, go ahead, you can clone it again, but remember to use option 14 to clear out the old dependencies folder first. If you find any further issues, please do let me know :+1:

**Comment by misaalanshori** [comment]
This keeps happening when airodump-ng is used:
[i] Let's run Airodump-ng for 5~ seconds to gather all the APs.
[i] Press CTRL+C once you see your target network.
[i] Once you're ready, press enter. >> 
[done] Successfully cleaned up.                                                                                                     

[+] Head to [m]enu or [q]uit? m/q >> 

it just immediately go to "[done] Successfully cleaned up.  [+] Head to [m]enu or [q]uit? m/q >> " after pressing enter.

**Comment by misaalanshori** [comment]
Everything works fine now. I'm not sure what happened..

**Comment by Sh3llcod3** [comment]
That's good to hear. I'd recommend hitting ctrl-c only once, otherwise it will exit. Once you feel like this issue is sorted, feel free to close it :+1:

**Comment by Sh3llcod3** [comment]
That's good to hear. I'd recommend hitting ctrl-c only once, otherwise it will exit. :+1:

**Comment by misaalanshori** [comment]
I will close it now. but i dont remember pressing ctrl-c before asked. maybe its some thing to do with my remote connection
