### ISSUE TITLE
On raspberry pi running kali linux

### ISSUE THREAD

**Issue by StephensCG** [Sh3llcod3/Airscript-ng#3]
Traceback (most recent call last):
  File "./airscript-ng.py", line 30, in <module>
    import modules
  File "/root/Airscript-ng/modules/__init__.py", line 23, in <module>
    from .manage_deps import *
  File "/root/Airscript-ng/modules/manage_deps.py", line 23, in <module>
    from .gui_elements import pickYesOrNo
  File "/root/Airscript-ng/modules/gui_elements.py", line 24, in <module>
    Tk().withdraw() #Don't show the root window
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by Sh3llcod3** [comment]
Hello,

Are you running a graphical desktop or is the Pi command line only?

I'll take a look ASAP, thanks for pointing out the issue 👍

**Comment by StephensCG** [comment]
I want to say command line only but ill try using a gui and get back to you

**Comment by DoughnutWuff** [comment]
Hi there,

That is caused either by you running the `./airscript-ng.py` file via command line only, or your Raspberry Pi has more than one framebuffer (RPi4 comes to mind :P), so you need to `export DISPLAY=:0`

Then it should run!

-Doughnut

**Comment by StephensCG** [comment]
I did get it to work further than that once i plugged and got a gui. I appreciate the assist. Keep Calm and Code On my friends
